# Generated by Django 2.1.3 on 2018-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2018-11-30'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_data',
            field=models.DateField(default='2018-11-30'),
        ),
    ]
