# Generated by Django 2.1.3 on 2019-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20181130_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-01-11'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_data',
            field=models.DateField(default='2019-01-11'),
        ),
    ]
