# Generated by Django 2.1.3 on 2019-01-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190111_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-01-12'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_data',
            field=models.DateField(default='2019-01-12'),
        ),
    ]
