# Generated by Django 2.1.3 on 2019-01-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190112_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2019-01-24'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_data',
            field=models.DateField(default='2019-01-24'),
        ),
    ]
